USE iFTS_Books;
GO
CREATE FULLTEXT STOPLIST NoFish_Stoplist
FROM SYSTEM STOPLIST
AUTHORIZATION dbo;

ALTER FULLTEXT STOPLIST NoFish_Stoplist
ADD 'fish' LANGUAGE 1033;

ALTER FULLTEXT INDEX ON dbo.Book
SET STOPLIST = NoFish_Stoplist;